version: '3.5'

services:
  mysql:
    image: mysql:5.7.23
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./mysql/data:/var/lib/mysql/:rw
    restart: always
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "qwe123!"

  redis:
    image: redis:5.0.3-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/etc/redis.conf:ro
      - ./redis/data:/data/:rw
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]
    networks:
      - backend

  api:
    container_name: api-test01
    build:
      context: ./api-test01
      dockerfile: Dockerfile
    ports:
      - "10230:10230" #10230 10230 맵핑
    environment:
      - NODE_ENV=dev
    volumes:
      - api-test01:/data/api-test01
    networks:
      - backend

  # gateway:
  #     container_name: api-test02
  #     build:
  #       context: ./api-test02
  #       dockerfile: Dockerfile
  #     ports:
  #       - "8080:80" #8080 8080 맵핑
  #     environment:
  #       - NODE_ENV=dev
  #     volumes:
  #       - api-test02:/data/api-test02
  #     networks:
  #       - backend

networks:
  backend:
    external: true

volumes:
  mysql:
  redis:
  api-test01:
  # api-test02: